# -*- coding: utf-8 -*-
#
# This file is part of refextract.
# Copyright (C) 2015, 2016, 2017, 2018 CERN.
#
# refextract is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# refextract is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with refextract; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

sudo: false

language: python

python:
  - '2.7'

addons:
  apt:
    packages:
      poppler-utils

install:
  - pip install --upgrade pip
  - pip install coveralls check-manifest
  - pip install pytest pytest-pep8 pytest-cov pytest-cache
  - pip install -e .[docs,tests]

script:
  - if [ "${TRAVIS_PYTHON_VERSION}" = "2.7" ]; then sphinx-build -qnNW docs docs/_build/html; fi
  - check-manifest
  - flake8 refextract tests
  - python setup.py test

after_success:
  - coveralls

notifications:
  email: false

deploy:
  provider: pypi
  user: inspirehep
  password:
    secure: VRWpn7B2QAtyNmQ3chD2Hi4lZNbQUB/aFx/p+hh/YN2W1/PiUSR7HuFyMw0fEdarDm7zTEUf576E58XWK6my9C1vVKssXQ43GnPVEk9ASau7GJN0Fnz+m3LJQze+ogiAeYVStVCxvZ/U6GU1LhwOV9WkZ5SyKzmXDkKdkPSBTJjkudK7D89hmx9m9gOq3mXWq6VisShHmO39uBtKxhWOYWfyOdfoB2jqpdT3AWZhjcbiVYGcRY5+GNL6WLLSB1Z97afW/DYVXP1IIU0ogJI9TaNl9ZmOJiN36+0LoLg+USikOXMECqqHT8MaYJ1+qP1wqy/kzJLujh6P2+hEeaSJalqbHxVDA4BybxsWnWDVGeYDCKiV+xtRpkD7OH+a2y8kCLe2Fx7Kgw3Z7zBoE/3q7ge2o9j0zSgrHQkTZhZGgdhkOdu2OEaZLTcVK+ekqkc/YbEBgCUWM7ltxz78FhfLSa18e0ZuIZTqoByLxuuKolwVBHAL+W7r6auRiT4jmtRn6Bll/oIZ/p71euWSLy20vB293e0/cZfXuGt/x+D5nu1R/yyjKcDnPesR82g3wyJgqlIiEij8FhvdH1QMqCtqKp+HUv0eOicrJiFYiMXhHAQZcY4KQBlgfx0wv43eV+SxX2RNHONqrHP6TgxVoQT3yOPrspwEi+oVsjp8Pp5ZxZg=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: inspirehep/refextract
    branch: master
