# This file is part of extractutils
# Copyright (C) 2015 CERN.
#
# extractutils is free software; you can redistribute it and/or
# modify it under the terms of the Revised BSD License; see LICENSE
# file for more details.

web:
  build: .
  command: python setup.py test
  volumes:
   - .:/code
